name: Comment Action
description: Create and edit comment on PR, issue
branding:
  icon: message-square
  color: blue
inputs:
  type:
    required: true
    description: create|edit
  token:
    required: true
    description: github token
  body:
    required: true
    description: comment body
  bad_text:
    required: true
    description: bad text
  comment_id:
    required: false
    description: required when edit, delete comment
  issue_number:
    required: false
    description: required when create comment
outputs:
  id:
    description: id of new comment
  body:
    description: body of new comment
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.type }}
    - ${{ inputs.token }}
    - ${{ inputs.body }}
    - ${{ inputs.bad_text }}
    - ${{ inputs.comment_id }}
    - ${{ inputs.issue_number }}
