name: Comment Scanner
author: Abhishek Jog (abhishekjog@gmail.com)
description: Parses comment to check if it contains disallowed content
inputs:
  msg: 
    description: Comment's message
    required: true
  check_for:
    description: Check for this string in the message
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.msg }}
    - ${{ inputs.check_for }}
